# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

lang: en-US
title: this.pavelluz.blog
email: arklogin@gmail.com
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gitpash.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: pavelluz
github_username: gitpash

# Build settings
markdown: kramdown
theme: jekyll-theme-basically-basic
gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

#Discuss
disqus:
  shortname: this-blog

defaults:
  - scope:
      path: ''
      path: 'assets/css'
    values:
      style: true
      comments: true
source: ''

#for deployment
destination: ../gitpash.github.io/
repository: 'gitpash/gitpash.github.io'

#location /Library/Ruby/Gems/2.0.0/gems/jekyll-theme-basically-basic-1.1.0

